//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfTemplate.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfTemplate.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   About に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellAbout {
            get {
                return ResourceManager.GetString("ShellAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellColor {
            get {
                return ResourceManager.GetString("ShellColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellLanguage {
            get {
                return ResourceManager.GetString("ShellLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Here is main contents area. Defined in MainRegion.cs and MainRegionViewModel.cs. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellMainRegionMessage {
            get {
                return ResourceManager.GetString("ShellMainRegionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellSettings {
            get {
                return ResourceManager.GetString("ShellSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Here is StatusBar message area. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellStatusBarMessage {
            get {
                return ResourceManager.GetString("ShellStatusBarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Theme に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ShellTheme {
            get {
                return ResourceManager.GetString("ShellTheme", resourceCulture);
            }
        }
    }
}
